"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Common utils used across the project
Contains date formats, enums etc
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Paksham:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PakshamEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Paksham.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PAKSHAM_UNKNOWN: _Paksham.ValueType  # 0
    KRISHNA: _Paksham.ValueType  # 1
    SHUKLA: _Paksham.ValueType  # 2

class Paksham(_Paksham, metaclass=_PakshamEnumTypeWrapper):
    """Enums are scoped for the entire file => They cannot have same "UNKNOWN" values across different enums
    Paksham based on the moon phase
    """

PAKSHAM_UNKNOWN: Paksham.ValueType  # 0
KRISHNA: Paksham.ValueType  # 1
SHUKLA: Paksham.ValueType  # 2
global___Paksham = Paksham

class _Thithi:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ThithiEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Thithi.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    THITHI_UNKNOWN: _Thithi.ValueType  # 0
    PRATHAMAI: _Thithi.ValueType  # 1
    DWITHIYAI: _Thithi.ValueType  # 2
    THRITHIYAI: _Thithi.ValueType  # 3
    CHATHURTHI: _Thithi.ValueType  # 4
    PANCHAMI: _Thithi.ValueType  # 5
    SASHTI: _Thithi.ValueType  # 6
    SAPTAMI: _Thithi.ValueType  # 7
    ASHTAMI: _Thithi.ValueType  # 8
    NAVAMI: _Thithi.ValueType  # 9
    DASAMI: _Thithi.ValueType  # 10
    EKADASI: _Thithi.ValueType  # 11
    DWADASI: _Thithi.ValueType  # 12
    THRAYODASI: _Thithi.ValueType  # 13
    CHATHURDASI: _Thithi.ValueType  # 14
    AMAVASYA: _Thithi.ValueType  # 15
    POURNAMI: _Thithi.ValueType  # 16

class Thithi(_Thithi, metaclass=_ThithiEnumTypeWrapper):
    """Day based on the moon's rotation around the earth"""

THITHI_UNKNOWN: Thithi.ValueType  # 0
PRATHAMAI: Thithi.ValueType  # 1
DWITHIYAI: Thithi.ValueType  # 2
THRITHIYAI: Thithi.ValueType  # 3
CHATHURTHI: Thithi.ValueType  # 4
PANCHAMI: Thithi.ValueType  # 5
SASHTI: Thithi.ValueType  # 6
SAPTAMI: Thithi.ValueType  # 7
ASHTAMI: Thithi.ValueType  # 8
NAVAMI: Thithi.ValueType  # 9
DASAMI: Thithi.ValueType  # 10
EKADASI: Thithi.ValueType  # 11
DWADASI: Thithi.ValueType  # 12
THRAYODASI: Thithi.ValueType  # 13
CHATHURDASI: Thithi.ValueType  # 14
AMAVASYA: Thithi.ValueType  # 15
POURNAMI: Thithi.ValueType  # 16
global___Thithi = Thithi

class _TamilMonth:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TamilMonthEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TamilMonth.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TAMIL_MONTH_UNKNOWN: _TamilMonth.ValueType  # 0
    CHITHIRAI: _TamilMonth.ValueType  # 1
    VAIKASI: _TamilMonth.ValueType  # 2
    AANI: _TamilMonth.ValueType  # 3
    AADI: _TamilMonth.ValueType  # 4
    AAVANI: _TamilMonth.ValueType  # 5
    PURATTASI: _TamilMonth.ValueType  # 6
    IYPASI: _TamilMonth.ValueType  # 7
    KARTHIGAI: _TamilMonth.ValueType  # 8
    MARGAZHI: _TamilMonth.ValueType  # 9
    THAI: _TamilMonth.ValueType  # 10
    MAASI: _TamilMonth.ValueType  # 11
    PANGUNI: _TamilMonth.ValueType  # 12

class TamilMonth(_TamilMonth, metaclass=_TamilMonthEnumTypeWrapper):
    """Tamil months of a year"""

TAMIL_MONTH_UNKNOWN: TamilMonth.ValueType  # 0
CHITHIRAI: TamilMonth.ValueType  # 1
VAIKASI: TamilMonth.ValueType  # 2
AANI: TamilMonth.ValueType  # 3
AADI: TamilMonth.ValueType  # 4
AAVANI: TamilMonth.ValueType  # 5
PURATTASI: TamilMonth.ValueType  # 6
IYPASI: TamilMonth.ValueType  # 7
KARTHIGAI: TamilMonth.ValueType  # 8
MARGAZHI: TamilMonth.ValueType  # 9
THAI: TamilMonth.ValueType  # 10
MAASI: TamilMonth.ValueType  # 11
PANGUNI: TamilMonth.ValueType  # 12
global___TamilMonth = TamilMonth

class _TamilStar:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TamilStarEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TamilStar.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TAMIL_STAR_UNKNOWN: _TamilStar.ValueType  # 0
    ASHWINI: _TamilStar.ValueType  # 1
    BARANI: _TamilStar.ValueType  # 2
    KRITHIGAI: _TamilStar.ValueType  # 3
    ROHINI: _TamilStar.ValueType  # 4
    MIRUGASEERISHAM: _TamilStar.ValueType  # 5
    THIRUVATHIRAI: _TamilStar.ValueType  # 6
    PUNARPOOSAM: _TamilStar.ValueType  # 7
    POOSAM: _TamilStar.ValueType  # 8
    AAYILYAM: _TamilStar.ValueType  # 9
    MAGAM: _TamilStar.ValueType  # 10
    POORAM: _TamilStar.ValueType  # 11
    UTHIRAM: _TamilStar.ValueType  # 12
    HASTHAM: _TamilStar.ValueType  # 13
    CHITTHIRAI: _TamilStar.ValueType  # 14
    """Changing the spelling to avoid enum conflicts with month from a single file scope"""
    SWATHI: _TamilStar.ValueType  # 15
    VISAGAM: _TamilStar.ValueType  # 16
    ANUSHAM: _TamilStar.ValueType  # 17
    KETTAI: _TamilStar.ValueType  # 18
    MOOLAM: _TamilStar.ValueType  # 19
    POORADAM: _TamilStar.ValueType  # 20
    UTHIRADAM: _TamilStar.ValueType  # 21
    THIRUVONAM: _TamilStar.ValueType  # 22
    AVITTAM: _TamilStar.ValueType  # 23
    SATHAYAM: _TamilStar.ValueType  # 24
    POORATTADHI: _TamilStar.ValueType  # 25
    UTHIRATTADHI: _TamilStar.ValueType  # 26
    REVATHI: _TamilStar.ValueType  # 27

class TamilStar(_TamilStar, metaclass=_TamilStarEnumTypeWrapper):
    """Tamil stars of a month"""

TAMIL_STAR_UNKNOWN: TamilStar.ValueType  # 0
ASHWINI: TamilStar.ValueType  # 1
BARANI: TamilStar.ValueType  # 2
KRITHIGAI: TamilStar.ValueType  # 3
ROHINI: TamilStar.ValueType  # 4
MIRUGASEERISHAM: TamilStar.ValueType  # 5
THIRUVATHIRAI: TamilStar.ValueType  # 6
PUNARPOOSAM: TamilStar.ValueType  # 7
POOSAM: TamilStar.ValueType  # 8
AAYILYAM: TamilStar.ValueType  # 9
MAGAM: TamilStar.ValueType  # 10
POORAM: TamilStar.ValueType  # 11
UTHIRAM: TamilStar.ValueType  # 12
HASTHAM: TamilStar.ValueType  # 13
CHITTHIRAI: TamilStar.ValueType  # 14
"""Changing the spelling to avoid enum conflicts with month from a single file scope"""
SWATHI: TamilStar.ValueType  # 15
VISAGAM: TamilStar.ValueType  # 16
ANUSHAM: TamilStar.ValueType  # 17
KETTAI: TamilStar.ValueType  # 18
MOOLAM: TamilStar.ValueType  # 19
POORADAM: TamilStar.ValueType  # 20
UTHIRADAM: TamilStar.ValueType  # 21
THIRUVONAM: TamilStar.ValueType  # 22
AVITTAM: TamilStar.ValueType  # 23
SATHAYAM: TamilStar.ValueType  # 24
POORATTADHI: TamilStar.ValueType  # 25
UTHIRATTADHI: TamilStar.ValueType  # 26
REVATHI: TamilStar.ValueType  # 27
global___TamilStar = TamilStar

class _Gender:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GenderEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Gender.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GENDER_UNKNOWN: _Gender.ValueType  # 0
    MALE: _Gender.ValueType  # 1
    FEMALE: _Gender.ValueType  # 2
    OTHER: _Gender.ValueType  # 3

class Gender(_Gender, metaclass=_GenderEnumTypeWrapper): ...

GENDER_UNKNOWN: Gender.ValueType  # 0
MALE: Gender.ValueType  # 1
FEMALE: Gender.ValueType  # 2
OTHER: Gender.ValueType  # 3
global___Gender = Gender

@typing.final
class GregorianDate(google.protobuf.message.Message):
    """Custom date to define Gregorian date format"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    YEAR_FIELD_NUMBER: builtins.int
    MONTH_FIELD_NUMBER: builtins.int
    DATE_FIELD_NUMBER: builtins.int
    year: builtins.int
    month: builtins.int
    date: builtins.int
    def __init__(
        self,
        *,
        year: builtins.int = ...,
        month: builtins.int = ...,
        date: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["date", b"date", "month", b"month", "year", b"year"]) -> None: ...

global___GregorianDate = GregorianDate

@typing.final
class TraditionalDate(google.protobuf.message.Message):
    """Custom date to define Tamil Hindu date format"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MONTH_FIELD_NUMBER: builtins.int
    STAR_FIELD_NUMBER: builtins.int
    PAKSHAM_FIELD_NUMBER: builtins.int
    THITHI_FIELD_NUMBER: builtins.int
    month: global___TamilMonth.ValueType
    star: global___TamilStar.ValueType
    paksham: global___Paksham.ValueType
    thithi: global___Thithi.ValueType
    def __init__(
        self,
        *,
        month: global___TamilMonth.ValueType = ...,
        star: global___TamilStar.ValueType = ...,
        paksham: global___Paksham.ValueType = ...,
        thithi: global___Thithi.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["month", b"month", "paksham", b"paksham", "star", b"star", "thithi", b"thithi"]) -> None: ...

global___TraditionalDate = TraditionalDate
