// source: proto/family_tree.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.family_tree.FamilyTree');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Map');
goog.require('jspb.Message');
goog.require('proto.family_tree.FamilyMember');
goog.require('proto.family_tree.FamilyUnit');
goog.require('proto.family_tree.Relationships');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.family_tree.FamilyTree = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.family_tree.FamilyTree.repeatedFields_, null);
};
goog.inherits(proto.family_tree.FamilyTree, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.family_tree.FamilyTree.displayName = 'proto.family_tree.FamilyTree';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.family_tree.FamilyTree.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.family_tree.FamilyTree.prototype.toObject = function(opt_includeInstance) {
  return proto.family_tree.FamilyTree.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.family_tree.FamilyTree} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.family_tree.FamilyTree.toObject = function(includeInstance, msg) {
  var f, obj = {
    membersMap: (f = msg.getMembersMap()) ? f.toObject(includeInstance, proto.family_tree.FamilyMember.toObject) : [],
    relationshipsMap: (f = msg.getRelationshipsMap()) ? f.toObject(includeInstance, proto.family_tree.Relationships.toObject) : [],
    familyUnitsList: jspb.Message.toObjectList(msg.getFamilyUnitsList(),
    proto.family_tree.FamilyUnit.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.family_tree.FamilyTree}
 */
proto.family_tree.FamilyTree.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.family_tree.FamilyTree;
  return proto.family_tree.FamilyTree.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.family_tree.FamilyTree} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.family_tree.FamilyTree}
 */
proto.family_tree.FamilyTree.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getMembersMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.family_tree.FamilyMember.deserializeBinaryFromReader, "", new proto.family_tree.FamilyMember());
         });
      break;
    case 2:
      var value = msg.getRelationshipsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.family_tree.Relationships.deserializeBinaryFromReader, "", new proto.family_tree.Relationships());
         });
      break;
    case 3:
      var value = new proto.family_tree.FamilyUnit;
      reader.readMessage(value,proto.family_tree.FamilyUnit.deserializeBinaryFromReader);
      msg.addFamilyUnits(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.family_tree.FamilyTree.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.family_tree.FamilyTree.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.family_tree.FamilyTree} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.family_tree.FamilyTree.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMembersMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.family_tree.FamilyMember.serializeBinaryToWriter);
  }
  f = message.getRelationshipsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.family_tree.Relationships.serializeBinaryToWriter);
  }
  f = message.getFamilyUnitsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.family_tree.FamilyUnit.serializeBinaryToWriter
    );
  }
};


/**
 * map<string, FamilyMember> members = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.family_tree.FamilyMember>}
 */
proto.family_tree.FamilyTree.prototype.getMembersMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.family_tree.FamilyMember>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      proto.family_tree.FamilyMember));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.family_tree.FamilyTree} returns this
 */
proto.family_tree.FamilyTree.prototype.clearMembersMap = function() {
  this.getMembersMap().clear();
  return this;};


/**
 * map<string, Relationships> relationships = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.family_tree.Relationships>}
 */
proto.family_tree.FamilyTree.prototype.getRelationshipsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.family_tree.Relationships>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.family_tree.Relationships));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.family_tree.FamilyTree} returns this
 */
proto.family_tree.FamilyTree.prototype.clearRelationshipsMap = function() {
  this.getRelationshipsMap().clear();
  return this;};


/**
 * repeated FamilyUnit family_units = 3;
 * @return {!Array<!proto.family_tree.FamilyUnit>}
 */
proto.family_tree.FamilyTree.prototype.getFamilyUnitsList = function() {
  return /** @type{!Array<!proto.family_tree.FamilyUnit>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.family_tree.FamilyUnit, 3));
};


/**
 * @param {!Array<!proto.family_tree.FamilyUnit>} value
 * @return {!proto.family_tree.FamilyTree} returns this
*/
proto.family_tree.FamilyTree.prototype.setFamilyUnitsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.family_tree.FamilyUnit=} opt_value
 * @param {number=} opt_index
 * @return {!proto.family_tree.FamilyUnit}
 */
proto.family_tree.FamilyTree.prototype.addFamilyUnits = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.family_tree.FamilyUnit, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.family_tree.FamilyTree} returns this
 */
proto.family_tree.FamilyTree.prototype.clearFamilyUnitsList = function() {
  return this.setFamilyUnitsList([]);
};


