// source: proto/utils.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.utils.TraditionalDate');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

goog.forwardDeclare('proto.utils.Paksham');
goog.forwardDeclare('proto.utils.TamilMonth');
goog.forwardDeclare('proto.utils.TamilStar');
goog.forwardDeclare('proto.utils.Thithi');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.utils.TraditionalDate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.utils.TraditionalDate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.utils.TraditionalDate.displayName = 'proto.utils.TraditionalDate';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.utils.TraditionalDate.prototype.toObject = function(opt_includeInstance) {
  return proto.utils.TraditionalDate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.utils.TraditionalDate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.utils.TraditionalDate.toObject = function(includeInstance, msg) {
  var f, obj = {
    month: jspb.Message.getFieldWithDefault(msg, 1, 0),
    star: jspb.Message.getFieldWithDefault(msg, 2, 0),
    paksham: jspb.Message.getFieldWithDefault(msg, 3, 0),
    thithi: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.utils.TraditionalDate}
 */
proto.utils.TraditionalDate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.utils.TraditionalDate;
  return proto.utils.TraditionalDate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.utils.TraditionalDate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.utils.TraditionalDate}
 */
proto.utils.TraditionalDate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.utils.TamilMonth} */ (reader.readEnum());
      msg.setMonth(value);
      break;
    case 2:
      var value = /** @type {!proto.utils.TamilStar} */ (reader.readEnum());
      msg.setStar(value);
      break;
    case 3:
      var value = /** @type {!proto.utils.Paksham} */ (reader.readEnum());
      msg.setPaksham(value);
      break;
    case 4:
      var value = /** @type {!proto.utils.Thithi} */ (reader.readEnum());
      msg.setThithi(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.utils.TraditionalDate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.utils.TraditionalDate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.utils.TraditionalDate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.utils.TraditionalDate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMonth();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getStar();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getPaksham();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getThithi();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
};


/**
 * optional TamilMonth month = 1;
 * @return {!proto.utils.TamilMonth}
 */
proto.utils.TraditionalDate.prototype.getMonth = function() {
  return /** @type {!proto.utils.TamilMonth} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.utils.TamilMonth} value
 * @return {!proto.utils.TraditionalDate} returns this
 */
proto.utils.TraditionalDate.prototype.setMonth = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional TamilStar star = 2;
 * @return {!proto.utils.TamilStar}
 */
proto.utils.TraditionalDate.prototype.getStar = function() {
  return /** @type {!proto.utils.TamilStar} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.utils.TamilStar} value
 * @return {!proto.utils.TraditionalDate} returns this
 */
proto.utils.TraditionalDate.prototype.setStar = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional Paksham paksham = 3;
 * @return {!proto.utils.Paksham}
 */
proto.utils.TraditionalDate.prototype.getPaksham = function() {
  return /** @type {!proto.utils.Paksham} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.utils.Paksham} value
 * @return {!proto.utils.TraditionalDate} returns this
 */
proto.utils.TraditionalDate.prototype.setPaksham = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional Thithi thithi = 4;
 * @return {!proto.utils.Thithi}
 */
proto.utils.TraditionalDate.prototype.getThithi = function() {
  return /** @type {!proto.utils.Thithi} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.utils.Thithi} value
 * @return {!proto.utils.TraditionalDate} returns this
 */
proto.utils.TraditionalDate.prototype.setThithi = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


